title: machine-yearning
description: Conversations on AI, databases, and knowledge representations
baseurl: ""
url: ""

# Build settings
markdown: kramdown
highlighter: rouge
theme: null # Disable default theme
remote_theme: null # Disable remote theme

# Include all files
include:
  - "*.md"
  - "**/*.md"
  - "**/.*"
  - "_chats"
  - "_chats/**/*"

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .gitignore
  - README.md
  
# Configure default layouts
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: "**/*.md"
    values:
      layout: "none"
      
# Plugins 
plugins:
  - jekyll-feed
  - jekyll-sitemap 