name: Update API.json

on:
  push:
    paths:
      - 'content/**'
  workflow_dispatch:  # Allow manual triggering

jobs:
  update-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for better git operations

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Generate API JSON
        run: node scripts/update-api.js
        continue-on-error: false

      - name: Commit and push changes
        run: |
          if [ -f api.json ]; then
            git config --global user.name 'GitHub Action'
            git config --global user.email 'action@github.com'
            git add api.json
            if git diff --staged --quiet; then
              echo "No changes to commit"
            else
              git commit -m "Update api.json with latest content files"
              git push
            fi
          else
            echo "Error: api.json was not generated"
            exit 1
          fi 