name: Update API.json

on:
  push:
    paths:
      - 'content/**'
  workflow_dispatch:  # Allow manual triggering

jobs:
  update-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Generate API JSON
        run: node scripts/update-api.js

      - name: Commit and push changes
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add api.json
          git diff --quiet && git diff --staged --quiet || git commit -m "Update api.json with latest content files"
          git push 